version: '3.6'

services:
    kainotomo-traefik:
      image: traefik:1.7.11
      restart: unless-stopped
      ports:
        - ${COMPOSE_PORT_HTTP}:80
        - ${COMPOSE_PORT_HTTPS}:443
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./traefik/traefik.toml:/traefik.toml
        - ./traefik/ssl/:/ssl/
        - ./logs:/logs
      container_name: kainotomo-traefik
      labels:
          - "traefik.enable=true"
          - "traefik.frontend.rule=Host:traefik.${COMPOSE_BASE_DOMAIN}"
          - "traefik.backend=traefik"
          - "traefik.port=8080"    
      restart: unless-stopped

    kainotomo-nginx:
      image: nginx:1.16.0-alpine
      container_name: kainotomo-nginx
      hostname: nginx
      volumes:
          - ../code_ph-money/:/code_ph-money/:rw
          #- ../code_emailvalidation/:/code_emailvalidation/:rw
          - ./include/nginx_local/conf.d/:/etc/nginx/conf.d/:ro
      depends_on:
          - kainotomo-php-fpm
      networks:
        default:
          aliases:
            - nginx-validation
      labels:
          - "traefik.enable=true"
          - "traefik.frontend.rule=HostRegexp:{catchall:.*}"
          - "traefik.frontend.priority=1"
          - "traefik.backend=kainotomo-nginx"
          - "traefik.port=80"    
      restart: unless-stopped

    kainotomo-mariadb:
      image: mariadb:10.4
      container_name: kainotomo-mariadb
      hostname: mariadb
      volumes:
        - ./backup:/backup
      ports:
        - ${COMPOSE_PORT_MYSQL}:3306
      environment:
        - MYSQL_ROOT_PASSWORD=root

    kainotomo-php-fpm:
      build:
        context: ./include/php-fpm
      container_name: kainotomo-php-fpm
      hostname: php-fpm
      volumes:
        # TimeFix
        #- /etc/localtime:/etc/localtime:ro
        # GeoIP
        #- ./docker_files/db_geoip/:/application/storage/app/geoip2/
        # CRON
        #- ./docker_files/cron/php-fpm_laravel_schedule:/etc/cron.d/cron
        - ../code_ph-money/:/code_ph-money/:rw
        #- ../code_emailverifier/:/code_emailverifier/:rw
    
    kainotomo-phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: kainotomo-phpmyadmin
      hostname: phpmyadmin
      environment:
        #- PMA_ARBITRARY=1
        - PMA_USER=root
        - PMA_PASSWORD=root
        - PMA_HOST=mariadb
      restart: unless-stopped
      depends_on:
        - kainotomo-mariadb
#      ports:
#        - 8080:80
      volumes:
        - /sessions
      labels:
          - "traefik.enable=true"
          - "traefik.frontend.rule=Host:phpmyadmin.${COMPOSE_BASE_DOMAIN}"
          - "traefik.backend=phpmyadmin"
          - "traefik.port=80"

    kainotomo-mailhog:
      image: mailhog/mailhog:latest
      container_name: kainotomo-mailhog
      restart: unless-stopped
      labels:
          - "traefik.enable=true"
          - "traefik.frontend.rule=Host:mailhog.${COMPOSE_BASE_DOMAIN}"
          - "traefik.backend=mailhog"
          - "traefik.port=8025"

    kainotomo-nodejs:
      image: node:11.10.0-alpine
      #build:
      #  context: ./include/vuejs-watch
      container_name: kainotomo-nodejs
      hostname: nodejs
      working_dir: /application
      volumes:
          - ../code_ph-money/:/code_ph-money/:rw
          #- ../code_emailverifier/:/code_emailverifier/:rw
      #restart: unless-stopped
      command: echo "Container ready."

    # kainotomo-netdata:
    #   image: netdata/netdata
    #   container_name: kainotomo-netdata
    #   hostname: netdata
    #   #ports:
    #   #  - 19999:19999
    #   cap_add:
    #     - SYS_PTRACE
    #   security_opt:
    #     - apparmor:unconfined
    #   volumes:
    #     - /proc:/host/proc:ro
    #     - /sys:/host/sys:ro
    #     - /var/run/docker.sock:/var/run/docker.sock:ro
    #   environment:
    #     - PGID=100
    #   labels:
    #       - "traefik.enable=true"
    #       - "traefik.frontend.rule=Host:netdata.${COMPOSE_BASE_DOMAIN}"
    #       - "traefik.backend=netdata"
    #       - "traefik.port=19999"
    #   restart: unless-stopped

#    kainotomo-geoip:
#      image: registry.kainotomo.com/geoip:latest
#      #build:
#      #  context: ./include/geoip
#      container_name: kainotomo-geoip
#      hostname: geoip
#      restart: unless-stopped
#      volumes:
#         - ./docker_files/db_geoip/:/usr/share/GeoIP/
#

networks:
  default:
    name: kainotomo-local-net
    driver: bridge
